if Rails.env.development? || Rails.env.test?

	Dotenv.require_keys(
		'AWS_ACCESS_KEY_ID',
		'AWS_BUCKET',
		'AWS_BUCKET_NAME',
		'AWS_REGION_NAME',
		'AWS_SECRET_ACCESS_KEY',
		'COMPANY_LOGO',
		'COMPANY_BACKGROUND',
		'DATABASE_URL',
		'DEVISE_SECRET_KEY',
		'PUSHER_APP_ID',
		'PUSHER_KEY',
		'PUSHER_SECRET',
		'PUSHER_CLUSTER',
		'TOKEN_EXPIRATION',
		'TOKEN_KEY_BASE',
		'DNA_API_URL',
		'DNA_API_KEY'
	)

	Dotenv.load(Rails.root.join('.env.development'))

end

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_BUCKET = ENV['AWS_BUCKET']
AWS_BUCKET_NAME = ENV['AWS_BUCKET_NAME']
AWS_REGION_NAME = ENV['AWS_REGION_NAME']
AWS_SECRET_ACCESS_KEY = ENV['AWS_SECRET_ACCESS_KEY']
COMPANY_LOGO = ENV['COMPANY_LOGO']
COMPANY_BACKGROUND = ENV['COMPANY_BACKGROUND']
DATABASE_URL = ENV['DATABASE_URL']
DEVISE_SECRET_KEY = ENV['DEVISE_SECRET_KEY']
DNA_API_KEY = ENV['DNA_API_KEY']
LANG = ENV['LANG']
MAILGUN_HOST = ENV['MAILGUN_HOST']
MAILGUN_PASS = ENV['MAILGUN_PASS']
MAILGUN_PORT = ENV['MAILGUN_PORT']
MAILGUN_USER = ENV['MAILGUN_USER']
PUSHER_APP_ID = ENV['PUSHER_APP_ID']
PUSHER_CLUSTER = ENV['PUSHER_CLUSTER']
PUSHER_KEY = ENV['PUSHER_KEY']
PUSHER_SECRET = ENV['PUSHER_SECRET']
RACK_ENV = ENV['RACK_ENV']
RAILS_ENV = ENV['RAILS_ENV']
RAILS_LOG_TO_STDOUT = ENV['RAILS_LOG_TO_STDOUT']
RAILS_SERVE_STATIC_FILES = ENV['RAILS_SERVE_STATIC_FILES']
SECRET_KEY_BASE = ENV['SECRET_KEY_BASE']
SITE_ADMIN_NAME = ENV['SITE_ADMIN_NAME']
SITE_SLUG = ENV['SITE_SLUG']
SITE_TITLE = ENV['SITE_TITLE']
SITE_URL = ENV['SITE_URL']
TOKEN_EXPIRATION = ENV['TOKEN_EXPIRATION']
TOKEN_KEY_BASE = ENV['TOKEN_KEY_BASE']
TWILIO_ACCOUNT_SID = ENV['TWILIO_ACCOUNT_SID']
TWILIO_PHONE_NUMBER = ENV['TWILIO_PHONE_NUMBER']
TWILIO_TOKEN_AUTH = ENV['TWILIO_TOKEN_AUTH']
